name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag and push Docker image
      run: |
        docker tag docker-hello-world:$(date +%s) ghcr.io/${{ github.repository_owner }}/docker-hello-world:latest
        docker push ghcr.io/${{ github.repository_owner }}/my-image-name:latest
